export const FETCH_ALL_CROPS_REQUEST = "FETCH_ALL_CROPS_REQUEST"; 
export const FETCH_ALL_CROPS_SUCCESS = "FETCH_ALL_CROPS_SUCCESS";
export const FETCH_ALL_CROPS_FAILURE = "FETCH_ALL_CROPS_FAILURE ";

// 
export const ADD_CROPS_REQUEST = "ADD_CROPS_REQUEST";
export const ADD_CROPS_SUCCESS = "ADD_CROPS_SUCCESS";
export const ADD_CROPS_FAILURE = "ADD_CROPS_FAILURE";

export const FETCH_ALL_CROPS_FARM_REQUEST = "FETCH_ALL_CROPS_FARM_REQUEST"; 
export const FETCH_ALL_CROPS_FARM_SUCCESS = "FETCH_ALL_CROPS_FARM_SUCCESSS";
export const FETCH_ALL_CROPS_FARM_FAILURE = "FETCH_ALL_CROPS_FARM_FAILURE ";

