export const FETCH_ALL_CROPS_REQUEST = "FETCH_ALL_CROPS_REQUEST";
export const FETCH_ALL_CROPS_SUCCESS = "FETCH_ALL_CROPS_SUCCESS";
export const FETCH_ALL_CROPS_FAILURE = "FETCH_ALL_CROPS_FAILURE ";

// 
export const ADD_CROP_TO_FARM_REQUEST = "ADD_CROP_TO_FARM_REQUEST";
export const ADD_CROP_TO_FARM_SUCCESS = "ADD_CROP_TO_FARM_SUCCESS";
export const ADD_CROP_TO_FARM_FAILURE = "ADD_CROP_TO_FARM_FAILURE";

export const FETCH_FARM_ALL_CROPS_REQUEST = "FETCH_FARM_ALL_CROPS_REQUEST";
export const FETCH_FARM_ALL_CROPS_SUCCESS = "FETCH_FARM_ALL_CROPS_SUCCESSS";
export const FETCH_FARM_ALL_CROPS_FAILURE = "FETCH_FARM_ALL_CROPS_FAILURE ";


// 
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOAD_AUTH_TOKEN = 'LOAD_AUTH_TOKEN';

//
//register actions
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_ALL_FARM_REQUEST = "FETCH_ALL_FARM_REQUEST";
export const FETCH_ALL_FARM_SUCCESS = "FETCH_ALL_FARM_SUCCESS";
export const FETCH_ALL_FARM_FAILURE = "FETCH_ALL_FARM_FAILURE";

//
export const ADD_FARM_REQUEST = "ADD_FARM_REQUEST";
export const ADD_FARM_SUCCESS = "ADD_FARM_SUCCESS";
export const ADD_FARM_FAILURE = "ADD_FARM_FAILURE";

//
export const FETCH_CROP_LIFECYCLE_REQUEST = "FETCH_CROP_LIFECYCLE_REQUEST";
export const FETCH_CROP_LIFECYCLE_SUCCESS = "FETCH_CROP_LIFECYCLE_SUCCESS";
export const FETCH_CROP_LIFECYCLE_FAILURE = "FETCH_CROP_LIFECYCLE_FAILURE ";

export const ADD_CROP_LIFECYCLE_REQUEST = "ADD_CROP_LIFECYCLE_REQUEST";
export const ADD_CROP_LIFECYCLE_SUCCESS = "ADD_CROP_LIFECYCLE_SUCCESS";
export const ADD_CROP_LIFECYCLE_FAILURE = "ADD_CROP_LIFECYCLE_FAILURE ";

export const FETCH_CROP_LIFECYCLE_DETAILS_REQUEST = "FETCH_CROP_LIFECYCLE_DETAILS_REQUEST";
export const FETCH_CROP_LIFECYCLE_DETAILS__SUCCESS = "FETCH_CROP_LIFECYCLE_DETAILS__SUCCESS";
export const FETCH_CROP_LIFECYCLE_DETAILS__FAILURE = "FETCH_CROP_LIFECYCLE_DETAILS__FAILURE";

export const UPDATE_CROP_LIFECYCLE_DETAILS_REQUEST = "UPDATE_CROP_LIFECYCLE_DETAILS_REQUEST";
export const UPDATE_CROP_LIFECYCLE_DETAILS_SUCCESS = "UPDATE_CROP_LIFECYCLE_DETAILS_SUCCESS";
export const UPDATE_CROP_LIFECYCLE_DETAILS_FAILURE = "UPDATE_CROP_LIFECYCLE_DETAILS_FAILURE";

//
export const CROP_LIFECYCLE_TRANSITION_REQUEST = "CROP_LIFECYCLE_TRANSITION_REQUEST";
export const CROP_LIFECYCLE_TRANSITION__SUCCESS = "CROP_LIFECYCLE_TRANSITION__SUCCESS";
export const CROP_LIFECYCLE_TRANSITION__FAILURE = "CROP_LIFECYCLE_TRANSITION__FAILURE";

///

export const UPDATE_CROP_LIFECYCLE_PARAMETERS_REQUEST = "UPDATE_CROP_LIFECYCLE_PARAMETERS_REQUEST";
export const UPDATE_CROP_LIFECYCLE_PARAMETERS_SUCCESS = "UPDATE_CROP_LIFECYCLE_PARAMETERS_SUCCESS";
export const UPDATE_CROP_LIFECYCLE_PARAMETERS_FAILURE = "UPDATE_CROP_LIFECYCLE_PARAMETERS_FAILURE";


export const UPDATE_CROP_LIFECYCLE_SCHEDULE_REQUEST = "UPDATE_CROP_LIFECYCLE_SCHEDULE_REQUEST";
export const UPDATE_CROP_LIFECYCLE_SCHEDULE_SUCCESS = "UPDATE_CROP_LIFECYCLE_SCHEDULE_SUCCESS";
export const UPDATE_CROP_LIFECYCLE_SCHEDULE_FAILURE = "UPDATE_CROP_LIFECYCLE_SCHEDULE_FAILURE";


//
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

// 
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

// 
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
//
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
//

export const UPDATE_MANAGE_CROP_REQUEST = "UPDATE_MANAGE_CROP_REQUEST";
export const UPDATE_MANAGE_CROP_SUCCESS = "UPDATE_MANAGE_CROP_SUCCESS";
export const UPDATE_MANAGE_CROP_FAILURE = "UPDATE_MANAGE_CROP_FAILURE";
//
export const DELETE_MANAGE_CROP_REQUEST = "DELETE_MANAGE_CROP_REQUEST";
export const DELETE_MANAGE_CROP_SUCCESS = "DELETE_MANAGE_CROP_SUCCESS";
export const DELETE_MANAGE_CROP_FAILURE = "DELETE_MANAGE_CROP_FAILURE";
//
export const UPDATE_FARM_REQUEST = "UPDATE_FARM_REQUEST";
export const UPDATE_FARM_SUCCESS = "UPDATE_FARM_SUCCESS";
export const UPDATE_FARM_FAILURE = "UPDATE_FARM_FAILURE";
//
export const DELETE_FARM_REQUEST = "DELETE_FARM_REQUEST";
export const DELETE_FARM_SUCCESS = "DELETE_FARM_SUCCESS";
export const DELETE_FARM_FAILURE = "DELETE_FARM_FAILURE";

// 
//

export const FETCH_ALL_DASHBOARD_HARVEST_REQUEST = "FETCH_ALL_DASHBOARD_HARVEST_REQUEST";
export const FETCH_ALL_DASHBOARD_HARVEST_SUCCESS = "FETCH_ALL_DASHBOARD_HARVEST_SUCCESS";   
export const FETCH_ALL_DASHBOARD_HARVEST_FAILURE = "FETCH_ALL_DASHBOARD_HARVEST_FAILURE";

 //

export  const FETCH_FARM_DETAILS_REQUEST = "FETCH_FARM_DETAILS_REQUEST";
export  const FETCH_FARM_DETAILS_SUCCESS = "FETCH_FARM_DETAILS_SUCCESS";
export  const FETCH_FARM_DETAILS_FAILURE = "FETCH_FARM_DETAILS_FAILURE";
//

export const LOAD_ROLE = 'LOAD_ROLE';
export const LOGOUT = 'LOGOUT';
//

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

//

export const FETCH_FARM_ALL_INVENTORY_REQUEST = "FETCH_FARM_ALL_INVENTORY_REQUEST";
export const FETCH_FARM_ALL_INVENTORY_SUCCESS = "FETCH_FARM_ALL_INVENTORY_SUCCESS";
export const FETCH_FARM_ALL_INVENTORY_FAILURE = "FETCH_FARM_ALL_INVENTORY_FAILURE";

///


export const ADD_FARM_INVENTORY_REQUEST = "ADD_FARM_INVENTORY_REQUEST";
export const ADD_FARM_INVENTORY_SUCCESS = "ADD_FARM_INVENTORY_SUCCESS";
export const ADD_FARM_INVENTORY_FAILURE = "ADD_FARM_INVENTORY_FAILURE";

//

export const UPDATE_FARM_INVENTORY_REQUEST = "UPDATE_FARM_INVENTORY_REQUEST";
export const UPDATE_FARM_INVENTORY_SUCCESS = "UPDATE_FARM_INVENTORY_SUCCESS";
export const UPDATE_FARM_INVENTORY_FAILURE = "UPDATE_FARM_INVENTORY_FAILURE";
//
export const DELETE_FARM_INVENTORY_REQUEST = "DELETE_FARM_INVENTORY_REQUEST";
export const DELETE_FARM_INVENTORY_SUCCESS = "DELETE_FARM_INVENTORY_SUCCESS";
export const DELETE_FARM_INVENTORY_FAILURE = "DELETE_FARM_INVENTORY_FAILURE";
//

export const FETCH_ALL_FARM_TASKS_REQUEST = "FETCH_ALL_FARM_TASKS_REQUEST";
export const FETCH_ALL_FARM_TASKS_SUCCESS = "FETCH_ALL_FARM_TASKS_SUCCESS";
export const FETCH_ALL_FARM_TASKS_FAILURE = "FETCH_ALL_FARM_TASKS_FAILURE";

//
export const ADD_FARM_TASKS_COMMENTS_REQUEST = "ADD_FARM_TASKS_COMMENTS_REQUEST";
export const ADD_FARM_TASKS_COMMENTS_SUCCESS = "ADD_FARM_TASKS_COMMENTS_SUCCESS";
export const ADD_FARM_TASKS_COMMENTS_FAILURE = "ADD_FARM_TASKS_COMMENTS_FAILURE";
///
export const ADD_TASKS_COMMENTS_REQUEST = "ADD_TASKS_COMMENTS_REQUEST";
export const ADD_TASKS_COMMENTS_SUCCESS = "ADD_TASKS_COMMENTS_SUCCESS";
export const ADD_TASKS_COMMENTS_FAILURE = "ADD_TASKS_COMMENTS_FAILURE";
//
export const FETCH_ALL_FARM_DASHBOARD_ZONE_REQUEST = "FETCH_ALL_FARM_DASHBOARD_ZONE_REQUEST";
export const FETCH_ALL_FARM_DASHBOARD_ZONE_SUCCESS = "FETCH_ALL_FARM_DASHBOARD_ZONE_SUCCESS";
export const FETCH_ALL_FARM_DASHBOARD_ZONE_FAILURE = "FETCH_ALL_FARM_DASHBOARD_ZONE_FAILURE";
//
export const ADD_FARM_DASHBOARD_ZONE_REQUEST = "ADD_FARM_DASHBOARD_ZONE_REQUEST";
export const ADD_FARM_DASHBOARD_ZONE_SUCCESS = "ADD_FARM_DASHBOARD_ZONE_SUCCESS";
export const ADD_FARM_DASHBOARD_ZONE_FAILURE = "ADD_FARM_DASHBOARD_ZONE_FAILURE";
//

export const UPDATE_FARM_DASHBOARD_ZONE_REQUEST = "UPDATE_FARM_DASHBOARD_ZONE_REQUEST";
export const UPDATE_FARM_DASHBOARD_ZONE_SUCCESS = "UPDATE_FARM_DASHBOARD_ZONE_SUCCESS";
export const UPDATE_FARM_DASHBOARD_ZONE_FAILURE = "UPDATE_FARM_DASHBOARD_ZONE_FAILURE";
//

export const DELETE_FARM_DASHBOARD_ZONE_REQUEST = "DELETE_FARM_DASHBOARD_ZONE_REQUEST";
export const DELETE_FARM_DASHBOARD_ZONE_SUCCESS = "DELETE_FARM_DASHBOARD_ZONE_SUCCESS";
export const DELETE_FARM_DASHBOARD_ZONE_FAILURE = "DELETE_FARM_DASHBOARD_ZONE_FAILURE";
//

export const FETCH_ALL_FARM_ZONE_REQUEST = "FETCH_ALL_FARM_ZONE_REQUEST";
export const FETCH_ALL_FARM_ZONE_SUCCESS = "FETCH_ALL_FARM_ZONE_SUCCESS";
export const FETCH_ALL_FARM_ZONE_FAILURE = "FETCH_ALL_FARM_ZONE_FAILURE";

//
export const FETCH_ALL_FARM_ZONE_DASHBOARD_REQUEST = "FETCH_ALL_FARM_ZONE_DASHBOARD_REQUEST";
export const FETCH_ALL_FARM_ZONE_DASHBOARD_SUCCESS = "FETCH_ALL_FARM_ZONE_DASHBOARD_SUCCESS";
export const FETCH_ALL_FARM_ZONE_DASHBOARD_FAILURE = "FETCH_ALL_FARM_ZONE_DASHBOARD_FAILURE";
//
export const FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_REQUEST = "FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_REQUEST";
export const FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_SUCCESS = "FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_SUCCESS";   
export const FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_FAILURE = "FETCH_ALL_FARM_ZONE_DASHBOARD_HARVEST_FAILURE";
//

export const ADD_FARM_DASHBOARD_ZONE_TASK_REQUEST = "ADD_FARM_DASHBOARD_ZONE_TASK_REQUEST";
export const ADD_FARM_DASHBOARD_ZONE_TASK_SUCCESS = "ADD_FARM_DASHBOARD_ZONE_TASK_SUCCESS";
export const ADD_FARM_DASHBOARD_ZONE_TASK_FAILURE = "ADD_FARM_DASHBOARD_ZONE_TASK_FAILURE";

//

export const ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_REQUEST = "ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_REQUEST";
export const ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_SUCCESS = "ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_SUCCESS";
export const ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_FAILURE = "ADD_FARM_DASHOBARD_ZONE_TASKS_COMMENT_FAILURE";

//

export const FETCH_ALL_ZONE_TASKS_REQUEST = "FETCH_ALL_ZONE_TASKS_REQUEST";
export const FETCH_ALL_ZONE_TASKS_SUCCESS = "FETCH_ALL_ZONE_TASKS_SUCCESS";
export const FETCH_ALL_ZONE_TASKS_FAILURE = "FETCH_ALL_FARM_TASKS_FAILURE";
//

export const ADD_ZONE_TASK_COMMENT_REQUEST = "ADD_ZONE_TASK_COMMENT_REQUEST";
export const ADD_ZONE_TASK_COMMENT_SUCCESS = "ADD_ZONE_TASK_COMMENT_SUCCESS";
export const ADD_ZONE_TASK_COMMENT_FAILURE = "ADD_ZONE_TASK_COMMENT_FAILURE";

//
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
//
export const FETCH_USER_PROFILE_DETAILS_REQUEST = 'FETCH_USER_PROFILE_DETAILS_REQUEST'
export const FETCH_USER_PROFILE_DETAILS_SUCCESS = 'FETCH_USER_PROFILE_DETAILS_SUCCESS'
export const FETCH_USER_PROFILE_DETAILS_FAILURE = 'FETCH_USER_PROFILE_DETAILS_FAILURE';
//
export const UPDATE_USER_PROFILE_DETAILS_REQUEST = 'UPDATE_USER_PROFILE_DETAILS_REQUEST'
export const UPDATE_USER_PROFILE_DETAILS_SUCCESS = 'UPDATE_USER_PROFILE_DETAILS_SUCCESS'
export const UPDATE_USER_PROFILE_DETAILS_FAILURE = 'UPDATE_USER_PROFILE_DETAILS_FAILURE';
//
export const UPDATE_USER_PHONE_PASSWORD_REQUEST = 'UPDATE_USER_PHONE_PASSWORD_REQUEST'
export const UPDATE_USER_PHONE_PASSWORD_SUCCESS = 'UPDATE_USER_PHONE_PASSWORD_SUCCESS'
export const UPDATE_USER_PHONE_PASSWORD_FAILURE = 'UPDATE_USER_PHONE_PASSWORD_FAILURE';
//
export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST'
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS'
export const UPDATE_USER_PASSWORD_FAILURE = 'UPDATE_USER_PASSWORD_FAILURE';
//
export const FETCH_ALL_ADMIN_DASHBOARD_REQUEST = 'FETCH_ALL_ADMIN_DASHBOARD_REQUEST'
export const FETCH_ALL_ADMIN_DASHBOARD_SUCCESS = 'FETCH_ALL_ADMIN_DASHBOARD_SUCCESS'
export const FETCH_ALL_ADMIN_DASHBOARD_FAILURE = 'FETCH_ALL_ADMIN_DASHBOARD_FAILURE';
//
export const ADD_ADMIN_ZONE_SENSORS_REQUEST = "ADD_ADMIN_ZONE_SENSORS_REQUEST";
export const ADD_ADMIN_ZONE_SENSORS_SUCCESS = "ADD_ADMIN_ZONE_SENSORS_SUCCESS";
export const ADD_ADMIN_ZONE_SENSORS_FAILURE = "ADD_ADMIN_ZONE_SENSORS_FAILURE";
//
export const DELETE_ADMIN_ZONE_SENSORS_REQUEST = "DELETE_ADMIN_ZONE_SENSORS_REQUEST";
export const DELETE_ADMIN_ZONE_SENSORS_SUCCESS = "DELETE_ADMIN_ZONE_SENSORS_SUCCESS";
export const DELETE_ADMIN_ZONE_SENSORS_FAILURE = "DELETE_ADMIN_ZONE_SENSORS_FAILURE";
//
export const FETCH_SENSOR_DATA_PUSHER_REQUEST = "FETCH_SENSOR_DATA_PUSHER_REQUEST";
export const FETCH_SENSOR_DATA_PUSHER_SUCCESS = "FETCH_SENSOR_DATA_PUSHER_SUCCESS";
export const FETCH_SENSOR_DATA_PUSHER_FAILURE = "FETCH_SENSOR_DATA_PUSHER_FAILURE";
//
export const FETCH_ALL_USER_ZONE_SENSORS_REQUEST = "FETCH_ALL_USER_ZONE_SENSORS_REQUEST";
export const FETCH_ALL_USER_ZONE_SENSORS_SUCCESS = "FETCH_ALL_USER_ZONE_SENSORS_SUCCESS";
export const FETCH_ALL_USER_ZONE_SENSORS_FAILURE = "FETCH_ALL_USER_ZONE_SENSORS_FAILURE";
//
export const FETCH_ALL_FARM_REPORTS_DATA_REQUEST = 'FETCH_ALL_FARM_REPORTS_DATA_REQUEST'
export const FETCH_ALL_FARM_REPORTS_DATA_SUCCESS = 'FETCH_ALL_FARM_REPORTS_DATA_SUCCESS'
export const FETCH_ALL_FARM_REPORTS_DATA_FAILURE = 'FETCH_ALL_FARM_REPORTS_DATA_FAILURE';
//
export const FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_REQUEST = 'FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_REQUEST'
export const FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_SUCCESS = 'FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_SUCCESS'
export const FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_FAILURE = 'FETCH_ALL_ZONE_SENSORS_REPORTS_DATA_FAILURE';
//
export const FETCH_RECENT_ZONE_SENSOR_DATA_REQUEST = 'FETCH_RECENT_ZONE_SENSOR_DATA_REQUEST'
export const FETCH_RECENT_ZONE_SENSOR_DATA_SUCCESS = 'FETCH_RECENT_ZONE_SENSOR_DATA_SUCCESS'
export const FETCH_RECENT_ZONE_SENSOR_DATA_FAILURE = 'FETCH_RECENT_ZONE_SENSOR_DATA_FAILURE';


//dashobard new actions 

export const FETCH_FARM_DASHBOARD_FARM_INFO_REQUEST = 'FETCH_FARM_DASHBOARD_FARM_INFO_REQUEST'
export const FETCH_FARM_DASHBOARD_FARM_INFO_SUCCESS = 'FETCH_FARM_DASHBOARD_FARM_INFO_SUCCESS'
export const FETCH_FARM_DASHBOARD_FARM_INFO_FAILURE = 'FETCH_FARM_DASHBOARD_FARM_INFO_FAILURE';
//
export const FETCH_FARM_DASHBOARD_CROP_SCHEDULES_REQUEST = 'FETCH_FARM_DASHBOARD_CROP_SCHEDULES_REQUEST'
export const FETCH_FARM_DASHBOARD_CROP_SCHEDULES_SUCCESS = 'FETCH_FARM_DASHBOARD_CROP_SCHEDULES_SUCCESS'
export const FETCH_FARM_DASHBOARD_CROP_SCHEDULES_FAILURE = 'FETCH_FARM_DASHBOARD_CROP_SCHEDULES_FAILURE';
//
export const FETCH_FARM_DASHBOARD_INFO_REQUEST = 'FETCH_FARM_DASHBOARD_INFO_REQUEST'
export const FETCH_FARM_DASHBOARD_INFO_SUCCESS = 'FETCH_FARM_DASHBOARD_INFO_SUCCESS'
export const FETCH_FARM_DASHBOARD_INFO_FAILURE = 'FETCH_FARM_DASHBOARD_INFO_FAILURE';
//

export const FETCH_FARM_DASHBOARD_TASK_REQUEST = 'FETCH_FARM_DASHBOARD_TASK_REQUEST'
export const FETCH_FARM_DASHBOARD_TASK_SUCCESS = 'FETCH_FARM_DASHBOARD_TASK_SUCCESS'
export const FETCH_FARM_DASHBOARD_TASK_FAILURE = 'FETCH_FARM_DASHBOARD_TASK_FAILURE';
//
export const FETCH_ZONE_DASHBOARD_ZONE_INFO_REQUEST = 'FETCH_ZONE_DASHBOARD_ZONE_INFO_REQUEST'
export const FETCH_FARM_DASHBOARD_ZONE_INFO_SUCCESS = 'FETCH_FARM_DASHBOARD_ZONE_INFO_SUCCESS'
export const FETCH_FARM_DASHBOARD_ZONE_INFO_FAILURE = 'FETCH_FARM_DASHBOARD_ZONE_INFO_FAILURE';
//
export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_REQUEST = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_REQUEST'
export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_SUCCESS = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_SUCCESS'
export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_FAILURE = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_CROP_FAILURE';

export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_REQUEST = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_REQUEST'
export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_SUCCESS = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_SUCCESS'
export const FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_FAILURE = 'FETCH_FARM_DASHBOARD_FARM_UTILIZATION_STAGES_FAILURE';

export const FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_REQUEST  = 'FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_REQUEST'
export const FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_SUCCESS  = 'FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_SUCCESS'
export const FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_FAILURE  = 'FETCH_FARM_DASHBOARD_ZONE_SENSOR_DATA_FAILURE';



//

//


export const FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_REQUEST = 'FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_REQUEST'
export const FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_SUCCESS = 'FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_SUCCESS'
export const FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_FAILURE = 'FETCH_ZONE_DASHBOARD_CROP_SCHEDULES_FAILURE';

export const FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_REQUEST = 'FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_REQUEST'
export const FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_SUCCESS = 'FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_SUCCESS'
export const FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_FAILURE = 'FETCH_ZONE_DASHBOARD_ZONE_TASK_SCHEDULES_FAILURE';

export const FETCH_ZONE_DASHBOARD_ZONE_SENSOR_REQUEST = 'FETCH_ZONE_DASHBOARD_ZONE_SENSOR_REQUEST'
export const FETCH_ZONE_DASHBOARD_ZONE_SENSOR_SUCCESS = 'FETCH_ZONE_DASHBOARD_ZONE_SENSOR_SUCCESS'
export const FETCH_ZONE_DASHBOARD_ZONE_SENSOR_FAILURE = 'FETCH_ZONE_DASHBOARD_ZONE_SENSOR_FAILURE';


export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_REQUEST = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_REQUEST'
export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_SUCCESS = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_SUCCESS'
export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_FAILURE = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_CROP_FAILURE';




//

export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_REQUEST = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_REQUEST'
export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_SUCCESS = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_SUCCESS'
export const FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_FAILURE = 'FETCH_ZONE_DASHBOARD_ZONE_UTILIZATION_STAGES_FAILURE';
///
export const FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_REQUEST  = 'FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_REQUEST'
export const FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_SUCCESS  = 'FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_SUCCESS'
export const FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_FAILURE  = 'FETCH_FARM_REPORTS_ZONE_AVERAGE_MORTALITY_FAILURE';
//
export const FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_REQUEST  = 'FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_REQUEST'
export const FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_SUCCESS  = 'FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_SUCCESS'
export const FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_FAILURE  = 'FETCH_FARM_REPORTS_FARM_AVERAGE_MORTALITY_FAILURE';


export const FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_REQUEST  = 'FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_REQUEST'
export const FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_SUCCESS  = 'FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_SUCCESS'
export const FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_FAILURE  = 'FETCH_FARM_REPORTS_FARM_TAT_TASK_CATEGORIES_FAILURE';


export const FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_REQUEST  = 'FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_REQUEST'
export const FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_SUCCESS  = 'FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_SUCCESS'
export const FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_FAILURE  = 'FETCH_FARM_REPORTS_ZONE_TAT_TASK_CATEGORIES_FAILURE';

//
export const FETCH_FARM_ZONE_SENSOR_DATA_REQUEST  = 'FETCH_FARM_ZONE_SENSOR_DATA_REQUEST'
export const FETCH_FARM_ZONE_SENSOR_DATA_SUCCESS  = 'FETCH_FARM_ZONE_SENSOR_DATA_SUCCESS'
export const FETCH_FARM_ZONE_SENSOR_DATA_FAILURE  = 'FETCH_FARM_ZONE_SENSOR_DATA_FAILURE';

//

















