export const FETCH_ALL_CROPS_REQUEST = "FETCH_ALL_CROPS_REQUEST";
export const FETCH_ALL_CROPS_SUCCESS = "FETCH_ALL_CROPS_SUCCESS";
export const FETCH_ALL_CROPS_FAILURE = "FETCH_ALL_CROPS_FAILURE ";

// 
export const ADD_CROP_TO_FARM_REQUEST = "ADD_CROP_TO_FARM_REQUEST";
export const ADD_CROP_TO_FARM_SUCCESS = "ADD_CROP_TO_FARM_SUCCESS";
export const ADD_CROP_TO_FARM_FAILURE = "ADD_CROP_TO_FARM_FAILURE";

export const FETCH_FARM_ALL_CROPS_REQUEST = "FETCH_FARM_ALL_CROPS_REQUEST";
export const FETCH_FARM_ALL_CROPS_SUCCESS = "FETCH_FARM_ALL_CROPS_SUCCESSS";
export const FETCH_FARM_ALL_CROPS_FAILURE = "FETCH_FARM_ALL_CROPS_FAILURE ";


// 
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOAD_AUTH_TOKEN = 'LOAD_AUTH_TOKEN';

//

export const FETCH_ALL_FARM_REQUEST = "FETCH_ALL_FARM_REQUEST";
export const FETCH_ALL_FARM_SUCCESS = "FETCH_ALL_FARM_SUCCESS";
export const FETCH_ALL_FARM_FAILURE = "FETCH_ALL_FARM_FAILURE";

//
export const ADD_FARM_REQUEST = "ADD_FARM_REQUEST";
export const ADD_FARM_SUCCESS = "ADD_FARM_SUCCESS";
export const ADD_FARM_FAILURE = "ADD_FARM_FAILURE";

//
export const FETCH_CROP_LIFECYCLE_REQUEST = "FETCH_CROP_LIFECYCLE_REQUEST";
export const FETCH_CROP_LIFECYCLE_SUCCESS = "FETCH_CROP_LIFECYCLE_SUCCESS";
export const FETCH_CROP_LIFECYCLE_FAILURE = "FETCH_CROP_LIFECYCLE_FAILURE ";

export const ADD_CROP_LIFECYCLE_REQUEST = "ADD_CROP_LIFECYCLE_REQUEST";
export const ADD_CROP_LIFECYCLE_SUCCESS = "ADD_CROP_LIFECYCLE_SUCCESS";
export const ADD_CROP_LIFECYCLE_FAILURE = "ADD_CROP_LIFECYCLE_FAILURE ";

export const FETCH_CROP_LIFECYCLE_DETAILS_REQUEST = "FETCH_CROP_LIFECYCLE_DETAILS_REQUEST";
export const FETCH_CROP_LIFECYCLE_DETAILS__SUCCESS = "FETCH_CROP_LIFECYCLE_DETAILS__SUCCESS";
export const FETCH_CROP_LIFECYCLE_DETAILS__FAILURE = "FETCH_CROP_LIFECYCLE_DETAILS__FAILURE";

export const CROP_LIFECYCLE_TRANSITION_REQUEST = "CROP_LIFECYCLE_TRANSITION_REQUEST";
export const CROP_LIFECYCLE_TRANSITION__SUCCESS = "CROP_LIFECYCLE_TRANSITION__SUCCESS";
export const CROP_LIFECYCLE_TRANSITION__FAILURE = "CROP_LIFECYCLE_TRANSITION__FAILURE";

///

export const UPDATE_CROP_LIFECYCLE_PARAMETERS_REQUEST = "UPDATE_CROP_LIFECYCLE_PARAMETERS_REQUEST";
export const UPDATE_CROP_LIFECYCLE_PARAMETERS_SUCCESS = "UPDATE_CROP_LIFECYCLE_PARAMETERS_SUCCESS";
export const UPDATE_CROP_LIFECYCLE_PARAMETERS_FAILURE = "UPDATE_CROP_LIFECYCLE_PARAMETERS_FAILURE";


export const UPDATE_CROP_LIFECYCLE_SCHEDULE_REQUEST = "UPDATE_CROP_LIFECYCLE_SCHEDULE_REQUEST";
export const UPDATE_CROP_LIFECYCLE_SCHEDULE_SUCCESS = "UPDATE_CROP_LIFECYCLE_SCHEDULE_SUCCESS";
export const UPDATE_CROP_LIFECYCLE_SCHEDULE_FAILURE = "UPDATE_CROP_LIFECYCLE_SCHEDULE_FAILURE";


//
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

// 
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

// 
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
//
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
//

export const UPDATE_MANAGE_CROP_REQUEST = "UPDATE_MANAGE_CROP_REQUEST";
export const UPDATE_MANAGE_CROP_SUCCESS = "UPDATE_MANAGE_CROP_SUCCESS";
export const UPDATE_MANAGE_CROP_FAILURE = "UPDATE_MANAGE_CROP_FAILURE";
//
export const DELETE_MANAGE_CROP_REQUEST = "DELETE_MANAGE_CROP_REQUEST";
export const DELETE_MANAGE_CROP_SUCCESS = "DELETE_MANAGE_CROP_SUCCESS";
export const DELETE_MANAGE_CROP_FAILURE = "DELETE_MANAGE_CROP_FAILURE";
//
export const UPDATE_FARM_REQUEST = "UPDATE_FARM_REQUEST";
export const UPDATE_FARM_SUCCESS = "UPDATE_FARM_SUCCESS";
export const UPDATE_FARM_FAILURE = "UPDATE_FARM_FAILURE";
//
export const DELETE_FARM_REQUEST = "DELETE_FARM_REQUEST";
export const DELETE_FARM_SUCCESS = "DELETE_FARM_SUCCESS";
export const DELETE_FARM_FAILURE = "DELETE_FARM_FAILURE";

// 
export const FETCH_ALL_DASHBOARD_FARM_REQUEST = "FETCH_ALL_DASHBOARD_FARM_REQUEST";
export const FETCH_ALL_DASHBOARD_FARM_SUCCESS = "FETCH_ALL_DASHBOARD_FARM_SUCCESS ";
export const FETCH_ALL_DASHBOARD_FARM_FAILURE = "FETCH_ALL_DASHBOARD_FARM_FAILURE";
//










